### ISSUE TITLE
Minor GUI errors

### ISSUE THREAD

**Issue by guofoo** [moxin-org/moly#235] opened 2024-08-24 07:09 UTC
As reported by @juntao: 
1 The “download success” box cannot be dismissed. 
2 The ```rust markdown is not correctly handled. At minimum, we should not display “rust” at the top. 
3 I cannot copy the code. I think we could even have a “run” button next to the code to directly launch the Rust playground to execute the code.

**Comment by Guocork** [comment] 2024-09-10 02:51
I‘am using  Linux system, and i couldn't reproduce the first and third issues, everything works fine on my end. However, i'am going to try adding a button to directly launch the Rust playground to execute the code.

**Comment by joulei** [comment] 2024-09-10 03:44
I have not managed to replicate the download popup issue in macOS either. Could you try again with the latest changes in `dev`?
I'm also able to copy the messages that include code blocks, are you unable to do so, or was this a request for a feature that allows copying only the code segment of the message? (which IMO we should add)

Regarding the Rust Playground launch, we've opened issue #247

**Comment by joulei** [comment] 2024-10-22 03:01
We're closing this as we've discussed these issues offline or separately here.

**Closed by joulei** 2024-10-22 03:01 UTC
