### ISSUE TITLE
No Model To Choose a Model drop down option after downloading

### ISSUE THREAD

**Issue by andodeki** [moxin-org/moly#44] opened 2024-04-25 20:45 UTC
I cant see downloaded Phi-3 Model in the Choose a Model drop down options even after restarting moxin.

I am on a Macbook.

> $ du -hs second-state/Phi-3-mini-4k-instruct-GGUF/*
2.5G	second-state/Phi-3-mini-4k-instruct-GGUF/Phi-3-mini-4k-instruct-Q5_K_S.gguf

<img width="1222" alt="Screenshot 2024-04-25 at 23 45 24" src="https://github.com/project-robius/moxin/assets/20384186/24a47825-ea97-4be2-8520-68d31c382d8c">

**Comment by jmbejar** [comment] 2024-04-26 20:32
Hi.. can you check (and, possibly, paste an screenshot) how this file looks in the Discovery section? I would like to confirm if you still have a Download button there or it is displayed as "Downloaded".

**Comment by andodeki** [comment] 2024-04-28 17:50
It shows the Download button for the model i downloaded 
The last one in the image below was downloaded.

<img width="1264" alt="Screenshot 2024-04-28 at 20 49 40" src="https://github.com/project-robius/moxin/assets/20384186/4c897d90-395b-4df0-a84f-cd1fd7a5b80e">

**Comment by jmbejar** [comment] 2024-05-01 13:40
Sorry for the delay but we are busy adding more features. We have noticed this problem more often, so we're currently working in a fix. Will update this issue soon.

**Comment by guofoo** [comment] 2024-05-13 20:59
This issue should be fixed already with the recent build. @andodeki Please confirm whether if it's still an issue.

**Comment by andodeki** [comment] 2024-05-17 18:32
Hello @guofoo , i have just tried the fix. Should i download a new model and delete the already deleted model?
Because the old model already downloaded does not still appear on the list of drop down menu.

**Comment by guofoo** [comment] 2024-05-19 01:38
Yes, the storage location has changed. You may remove the old downloaded model files and start fresh. Then download your first new model, it should appear in the model drop down

**Comment by andodeki** [comment] 2024-05-22 21:12
Ok like before i had started a new download and paused. The paused model wont continue to download even after clean builds.

<img width="1175" alt="Screenshot 2024-05-23 at 00 10 49" src="https://github.com/project-robius/moxin/assets/20384186/c1347076-53a9-460c-9704-709da0bbf8b2">

**Comment by jmbejar** [comment] 2024-06-04 17:57
Hi @andodeki .. I wonder if you're able to see the resume & stop buttons that should appear at the right of the progress bar for each download. 

<img width="1270" alt="image" src="https://github.com/moxin-org/moxin/assets/487140/c659fef3-4ac0-45ab-906c-c1bd28c7d9fb">

In theory, you may use the play button to resume the download, but maybe you're in a screen resolution where those buttons are hidden? Just confirmed on my end this part of the screen is not properly adapting to the available screen width.

Could you confirm it?

**Comment by andodeki** [comment] 2024-06-06 19:52
Oh yeah i have changed the resolution to much smaller and i can see the play button

**Comment by kevinaboos** [comment] 2024-06-07 21:10
@andodeki we just changed the default directories used by Moxin to be more canonical (by using the standardized OS-preferred dirs for app data, preferences, etc).

Hopefully everything works now, give it a try with the latest commit on `main` to see if you can download and observe models in the drop down menu.

**Comment by joulei** [comment] 2024-10-24 07:48
As other have mentioned the lasting issue seems to be with the directory change. This should be working by now.

**Closed by joulei** 2024-10-24 07:48 UTC
